import 'package:json_annotation/json_annotation.dart';

part 'dishesresponsemodel.g.dart';

@JsonSerializable(
    checked: true,
    explicitToJson: true,
    fieldRename: FieldRename.snake,
    includeIfNull: false)
class Autogenerated {
  Autogenerated();
  String restaurantId;
  String restaurantName;
  String restaurantImage;
  String tableId;
  String tableName;
  String branchName;
  String nexturl;
  List<TableMenuList> tableMenuList;

  @override
  List<Object> get props => [
        restaurantId,
        restaurantName,
        restaurantImage,
        tableId,
        tableName,
        tableName,
        branchName,
        nexturl,
        tableMenuList
      ];
  factory Autogenerated.fromJson(Map<String, dynamic> json) =>
      _$AutogeneratedFromJson(json);

  Map<String, dynamic> toJson() => _$AutogeneratedToJson(this);
}

@JsonSerializable(
    checked: true,
    explicitToJson: true,
    fieldRename: FieldRename.snake,
    includeIfNull: false)
class TableMenuList {
  TableMenuList();
  String menuCategory;
  String menuCategoryId;
  String menuCategoryImage;
  String nexturl;
  List<CategoryDishes> categoryDishes;

  @override
  List<Object> get props => [
        menuCategory,
        menuCategoryId,
        menuCategoryImage,
        nexturl,
        categoryDishes,
      ];
  factory TableMenuList.fromJson(Map<String, dynamic> json) =>
      _$TableMenuListFromJson(json);

  Map<String, dynamic> toJson() => _$TableMenuListToJson(this);
}

@JsonSerializable(
    checked: true,
    explicitToJson: true,
    fieldRename: FieldRename.snake,
    includeIfNull: false)
class CategoryDishes {
  CategoryDishes();
  String dishId;
  String dishName;
  double dishPrice;
  String dishImage;
  String dishCurrency;
  double dishCalories;
  String dishDescription;
  bool dishAvailability;
  int dishType;
  String nexturl;
  int quantity;
  List<AddonCat> addonCat;
  @override
  List<Object> get props => [
        dishId,
        dishName,
        dishPrice,
        dishImage,
        dishCurrency,
        dishCalories,
        dishDescription,
        dishAvailability,
        dishType,
        nexturl,
        addonCat,
      ];
  factory CategoryDishes.fromJson(Map<String, dynamic> json) =>
      _$CategoryDishesFromJson(json);

  Map<String, dynamic> toJson() => _$CategoryDishesToJson(this);
}

@JsonSerializable(
    checked: true,
    explicitToJson: true,
    fieldRename: FieldRename.snake,
    includeIfNull: false)
class AddonCat {
  AddonCat();
  String addonCategory;
  String addonCategoryId;
  int addonSelection;
  String nexturl;
  List<Addons> addons;

  @override
  List<Object> get props => [
        addonCategory,
        addonCategoryId,
        addonSelection,
        nexturl,
        addons,
      ];
  factory AddonCat.fromJson(Map<String, dynamic> json) =>
      _$AddonCatFromJson(json);

  Map<String, dynamic> toJson() => _$AddonCatToJson(this);
}

@JsonSerializable(
    checked: true,
    explicitToJson: true,
    fieldRename: FieldRename.snake,
    includeIfNull: false)
class Addons {
  Addons();
  String dishId;
  String dishName;
  int dishPrice;
  String dishImage;
  String dishCurrency;
  int dishCalories;
  String dishDescription;
  bool dishAvailability;
  int dishType;

  @override
  List<Object> get props => [
        dishId,
        dishName,
        dishPrice,
        dishImage,
        dishCurrency,
        dishCalories,
        dishDescription,
        dishAvailability,
        dishType
      ];
  factory Addons.fromJson(Map<String, dynamic> json) => _$AddonsFromJson(json);

  Map<String, dynamic> toJson() => _$AddonsToJson(this);
}
