// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'dishesresponsemodel.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Autogenerated _$AutogeneratedFromJson(Map<String, dynamic> json) {
  return $checkedNew('Autogenerated', json, () {
    final val = Autogenerated();
    $checkedConvert(
        json, 'restaurant_id', (v) => val.restaurantId = v as String);
    $checkedConvert(
        json, 'restaurant_name', (v) => val.restaurantName = v as String);
    $checkedConvert(
        json, 'restaurant_image', (v) => val.restaurantImage = v as String);
    $checkedConvert(json, 'table_id', (v) => val.tableId = v as String);
    $checkedConvert(json, 'table_name', (v) => val.tableName = v as String);
    $checkedConvert(json, 'branch_name', (v) => val.branchName = v as String);
    $checkedConvert(json, 'nexturl', (v) => val.nexturl = v as String);
    $checkedConvert(
        json,
        'table_menu_list',
        (v) => val.tableMenuList = (v as List)
            ?.map((e) => e == null
                ? null
                : TableMenuList.fromJson(e as Map<String, dynamic>))
            ?.toList());
    return val;
  }, fieldKeyMap: const {
    'restaurantId': 'restaurant_id',
    'restaurantName': 'restaurant_name',
    'restaurantImage': 'restaurant_image',
    'tableId': 'table_id',
    'tableName': 'table_name',
    'branchName': 'branch_name',
    'tableMenuList': 'table_menu_list'
  });
}

Map<String, dynamic> _$AutogeneratedToJson(Autogenerated instance) {
  final val = <String, dynamic>{};

  void writeNotNull(String key, dynamic value) {
    if (value != null) {
      val[key] = value;
    }
  }

  writeNotNull('restaurant_id', instance.restaurantId);
  writeNotNull('restaurant_name', instance.restaurantName);
  writeNotNull('restaurant_image', instance.restaurantImage);
  writeNotNull('table_id', instance.tableId);
  writeNotNull('table_name', instance.tableName);
  writeNotNull('branch_name', instance.branchName);
  writeNotNull('nexturl', instance.nexturl);
  writeNotNull('table_menu_list',
      instance.tableMenuList?.map((e) => e?.toJson())?.toList());
  return val;
}

TableMenuList _$TableMenuListFromJson(Map<String, dynamic> json) {
  return $checkedNew('TableMenuList', json, () {
    final val = TableMenuList();
    $checkedConvert(
        json, 'menu_category', (v) => val.menuCategory = v as String);
    $checkedConvert(
        json, 'menu_category_id', (v) => val.menuCategoryId = v as String);
    $checkedConvert(json, 'menu_category_image',
        (v) => val.menuCategoryImage = v as String);
    $checkedConvert(json, 'nexturl', (v) => val.nexturl = v as String);
    $checkedConvert(
        json,
        'category_dishes',
        (v) => val.categoryDishes = (v as List)
            ?.map((e) => e == null
                ? null
                : CategoryDishes.fromJson(e as Map<String, dynamic>))
            ?.toList());
    return val;
  }, fieldKeyMap: const {
    'menuCategory': 'menu_category',
    'menuCategoryId': 'menu_category_id',
    'menuCategoryImage': 'menu_category_image',
    'categoryDishes': 'category_dishes'
  });
}

Map<String, dynamic> _$TableMenuListToJson(TableMenuList instance) {
  final val = <String, dynamic>{};

  void writeNotNull(String key, dynamic value) {
    if (value != null) {
      val[key] = value;
    }
  }

  writeNotNull('menu_category', instance.menuCategory);
  writeNotNull('menu_category_id', instance.menuCategoryId);
  writeNotNull('menu_category_image', instance.menuCategoryImage);
  writeNotNull('nexturl', instance.nexturl);
  writeNotNull('category_dishes',
      instance.categoryDishes?.map((e) => e?.toJson())?.toList());
  return val;
}

CategoryDishes _$CategoryDishesFromJson(Map<String, dynamic> json) {
  return $checkedNew('CategoryDishes', json, () {
    final val = CategoryDishes();
    $checkedConvert(json, 'dish_id', (v) => val.dishId = v as String);
    $checkedConvert(json, 'dish_name', (v) => val.dishName = v as String);
    $checkedConvert(
        json, 'dish_price', (v) => val.dishPrice = (v as num)?.toDouble());
    $checkedConvert(json, 'dish_image', (v) => val.dishImage = v as String);
    $checkedConvert(
        json, 'dish_currency', (v) => val.dishCurrency = v as String);
    $checkedConvert(json, 'dish_calories',
        (v) => val.dishCalories = (v as num)?.toDouble());
    $checkedConvert(
        json, 'dish_description', (v) => val.dishDescription = v as String);
    $checkedConvert(
        json, 'dish_availability', (v) => val.dishAvailability = v as bool);
    $checkedConvert(json, 'dish_type', (v) => val.dishType = v as int);
    $checkedConvert(json, 'nexturl', (v) => val.nexturl = v as String);
    $checkedConvert(
        json,
        'addon_cat',
        (v) => val.addonCat = (v as List)
            ?.map((e) =>
                e == null ? null : AddonCat.fromJson(e as Map<String, dynamic>))
            ?.toList());
    return val;
  }, fieldKeyMap: const {
    'dishId': 'dish_id',
    'dishName': 'dish_name',
    'dishPrice': 'dish_price',
    'dishImage': 'dish_image',
    'dishCurrency': 'dish_currency',
    'dishCalories': 'dish_calories',
    'dishDescription': 'dish_description',
    'dishAvailability': 'dish_availability',
    'dishType': 'dish_type',
    'addonCat': 'addon_cat'
  });
}

Map<String, dynamic> _$CategoryDishesToJson(CategoryDishes instance) {
  final val = <String, dynamic>{};

  void writeNotNull(String key, dynamic value) {
    if (value != null) {
      val[key] = value;
    }
  }

  writeNotNull('dish_id', instance.dishId);
  writeNotNull('dish_name', instance.dishName);
  writeNotNull('dish_price', instance.dishPrice);
  writeNotNull('dish_image', instance.dishImage);
  writeNotNull('dish_currency', instance.dishCurrency);
  writeNotNull('dish_calories', instance.dishCalories);
  writeNotNull('dish_description', instance.dishDescription);
  writeNotNull('dish_availability', instance.dishAvailability);
  writeNotNull('dish_type', instance.dishType);
  writeNotNull('nexturl', instance.nexturl);
  writeNotNull(
      'addon_cat', instance.addonCat?.map((e) => e?.toJson())?.toList());
  return val;
}

AddonCat _$AddonCatFromJson(Map<String, dynamic> json) {
  return $checkedNew('AddonCat', json, () {
    final val = AddonCat();
    $checkedConvert(
        json, 'addon_category', (v) => val.addonCategory = v as String);
    $checkedConvert(
        json, 'addon_category_id', (v) => val.addonCategoryId = v as String);
    $checkedConvert(
        json, 'addon_selection', (v) => val.addonSelection = v as int);
    $checkedConvert(json, 'nexturl', (v) => val.nexturl = v as String);
    $checkedConvert(
        json,
        'addons',
        (v) => val.addons = (v as List)
            ?.map((e) =>
                e == null ? null : Addons.fromJson(e as Map<String, dynamic>))
            ?.toList());
    return val;
  }, fieldKeyMap: const {
    'addonCategory': 'addon_category',
    'addonCategoryId': 'addon_category_id',
    'addonSelection': 'addon_selection'
  });
}

Map<String, dynamic> _$AddonCatToJson(AddonCat instance) {
  final val = <String, dynamic>{};

  void writeNotNull(String key, dynamic value) {
    if (value != null) {
      val[key] = value;
    }
  }

  writeNotNull('addon_category', instance.addonCategory);
  writeNotNull('addon_category_id', instance.addonCategoryId);
  writeNotNull('addon_selection', instance.addonSelection);
  writeNotNull('nexturl', instance.nexturl);
  writeNotNull('addons', instance.addons?.map((e) => e?.toJson())?.toList());
  return val;
}

Addons _$AddonsFromJson(Map<String, dynamic> json) {
  return $checkedNew('Addons', json, () {
    final val = Addons();
    $checkedConvert(json, 'dish_id', (v) => val.dishId = v as String);
    $checkedConvert(json, 'dish_name', (v) => val.dishName = v as String);
    $checkedConvert(json, 'dish_price', (v) => val.dishPrice = v as int);
    $checkedConvert(json, 'dish_image', (v) => val.dishImage = v as String);
    $checkedConvert(
        json, 'dish_currency', (v) => val.dishCurrency = v as String);
    $checkedConvert(json, 'dish_calories', (v) => val.dishCalories = v as int);
    $checkedConvert(
        json, 'dish_description', (v) => val.dishDescription = v as String);
    $checkedConvert(
        json, 'dish_availability', (v) => val.dishAvailability = v as bool);
    $checkedConvert(json, 'dish_type', (v) => val.dishType = v as int);
    return val;
  }, fieldKeyMap: const {
    'dishId': 'dish_id',
    'dishName': 'dish_name',
    'dishPrice': 'dish_price',
    'dishImage': 'dish_image',
    'dishCurrency': 'dish_currency',
    'dishCalories': 'dish_calories',
    'dishDescription': 'dish_description',
    'dishAvailability': 'dish_availability',
    'dishType': 'dish_type'
  });
}

Map<String, dynamic> _$AddonsToJson(Addons instance) {
  final val = <String, dynamic>{};

  void writeNotNull(String key, dynamic value) {
    if (value != null) {
      val[key] = value;
    }
  }

  writeNotNull('dish_id', instance.dishId);
  writeNotNull('dish_name', instance.dishName);
  writeNotNull('dish_price', instance.dishPrice);
  writeNotNull('dish_image', instance.dishImage);
  writeNotNull('dish_currency', instance.dishCurrency);
  writeNotNull('dish_calories', instance.dishCalories);
  writeNotNull('dish_description', instance.dishDescription);
  writeNotNull('dish_availability', instance.dishAvailability);
  writeNotNull('dish_type', instance.dishType);
  return val;
}
