import 'package:flutter/material.dart';
import 'package:newproject/app/locator.dart';
import 'package:newproject/core/data/api/apicall/dishesapicall.dart';
import 'package:newproject/core/data/api/models/api_response.dart';
import 'package:newproject/core/data/api_model/dishesreponsemodel/dishesresponsemodel.dart';
import 'package:stacked/stacked.dart';

class userhomeviewmodel extends BaseViewModel {
  Autogenerated tablemenulist = Autogenerated();
  List<CategoryDishes> newcategoryDishes;
  TabController tabcontroller;

  Apicall() async {
    ApiResponse response = await locator<dishesapicall>().getdishes();
    if (response != null) {
      tablemenulist = Autogenerated.fromJson(response.jsonArray[0]);
      print(tablemenulist.toString());
      notifyListeners();
    }
  }

  Notify() {
    notifyListeners();
  }

  controller(TabController tab) {
    tab.addListener(() {
      notifyListeners();
    });
  }

   additem(int index1,int index2) {
     int i = 0;
    if(tablemenulist.tableMenuList[index1].categoryDishes[index2].quantity == null){
      i= 1;
    }else{
      i = tablemenulist.tableMenuList[index1].categoryDishes[index2].quantity+1;
    }
    tablemenulist.tableMenuList[index1].categoryDishes[index2].quantity =i;
    notifyListeners();



  }

  deleteitem(int indexx, int index) {
    int i=0;
    if(tablemenulist.tableMenuList[indexx].categoryDishes[index].quantity == null){
      i= 0;
    }else if(tablemenulist.tableMenuList[indexx].categoryDishes[index].quantity >0 ){
      i = tablemenulist.tableMenuList[indexx].categoryDishes[index].quantity-1;
    }
    tablemenulist.tableMenuList[indexx].categoryDishes[index].quantity =i;
    notifyListeners();

  }
}
